### PR TITLE
[RA-3470] added new ugly checks

### PR DESCRIPTION
**Pull request by HrantTadevosyan**
The complete description can be found here:
https://confluence.slc.efscloud.net/display/~htadevosyan/Reverse+Engineering+VSS

### CODE REVIEW

**Comment by AnatolyZ** [comment]
@HrantTadevosyan We also need these changes in vshadow project, which is used for some legacy versions of Windows.

**Comment by HrantTadevosyan** [comment]
@AnatolyZ I added it there but then I realized that we probably don't need it as that nested issue can not occur on legacy versions, from MSDN:

image

Should I remove that commit back or is it OK to keep it, also what about the `/Win7Samples/vShadow`. Don't we need it there too?

**Comment by AnatolyZ** [comment]
Since the error is possible (or can be detected) only on systems more recent than WS2008. let's remove it from vshadow. The less ugly code the better)
Win7 samples are not needed we use only these projects:
https://github.com/Axcient/ReplibitAgent/blob/06cc7ebdc3b793f59bd40a1cb65b505c0c6dae29/scripts/ci-build-windows.ps1#L461

**Comment by HrantTadevosyan** [comment]
Reverted back the last commit

**Review by AnatolyZ — APPROVED** [review]

**Pull request closed without merging**
